# Generated by Django 6.0.4 on 2026-04-30 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='characterprogress',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characterprogress',
            name='next_review',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='mode',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='script',
            field=models.CharField(choices=[('hiragana', 'Hiragana'), ('katakana', 'Katakana'), ('kana', 'Hiragana + Katakana'), ('kanji', 'Kanji')], max_length=20),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
